name: 'ESLint (JS/TS) Action '
description: 'Lints JavaScript/TypeScript code.'
author: 'iCrawl'
branding:
  icon: check-circle
  color: yellow
inputs:
  job-name:
    description: 'Optional name of the annotation author.'
  lint-all:
    description: 'Lint all files.'
  custom-glob:
    description: 'Custom glob to overwrite which files to lint. Delimited by a comma(,). This option only works with lint-all enabled.'
runs:
  using: 'node12'
  main: 'dist/index.js'
