name: 'ESLint (JS/TS) Action '
description: 'Lints JavaScript/TypeScript code.'
author: 'iCrawl'
branding:
  icon: check-circle
  color: yellow
inputs:
  job-name:
    description: 'Name of the annotation author.'
    required: false
    default: 'eslint'
  lint-all:	
    description: 'Lint all files.'
    default: false
    required: false
  custom-glob:
    description: 'Custom glob to overwrite which files to lint. Delimited by a comma(,).'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
